stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src
        ln -s `pwd` /go/src/pipeline-test-demo
        cd /go/src/pipeline-test-demo
        go build -o pipeline-test-demo main.go
        cat
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pipeline-test-demo
      pushRemote: true
      registry: 127.0.0.1:34943
      callbackScript: /callbackscript/java.sh
      callbackScriptParams: abc def
    env:
      PLUGIN_DEBUG: "true"
timeout: 60
notification: {}
