stages:
- name: build-src
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src
        echo 1
- name: publish-src
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pipeline-test-demo
      pushRemote: true
      registry: registry.docker.i.fbank.com
      callbackScript: /callbackscript/java.sh
    env:
      PLUGIN_DEBUG: "true"
timeout: 60
notification: {}
